### ISSUE TITLE
enigma2 compile

### ISSUE THREAD

**Issue by persianpros** [PLi-metas/meta-linkdroid#3]
Hi my friend,

Would you please help me and try compiling a new image? enigma2 gives me error ...

Regards,
Persian Prince

**Comment by moham96** [comment]
@persianpros I'm rebuilding my dev environment, give me a day or two and I will have a look.
just curious why you keep updating this layer since the dvb part doesn't work?
I gave up on the dvb part in the vendor kernel(too many errors, everything is written in a custom fashion, this probably why Wetek also gave up on enigm2 support) instead, I'm waiting for the mainline kernel to gain dvb subsystem support.

Regards

**Comment by persianpros** [comment]
meta-linkdroid is about alien5 too but I can't compile for alien5 too :( also maintaining regularly is easier for me to do it after a long time :)

If you have a raspberry pi come and and join us: https://github.com/PLi-metas/meta-raspberrypi

**Comment by moham96** [comment]
@persianpros  Do you have a bisect? did it compile before?

**Comment by persianpros** [comment]
It's ok now with this patch: https://github.com/PLi-metas/pli-extras/commit/72d7b19ba82f541800790d591a3afcba0a9bcd72
